#!/bin/sh
#Script to prepare WinXound
echo "Preconfiguring WinXound for ./configure ..."
echo "libtoolize ..."
libtoolize
echo "aclocal ..."
aclocal
echo "autoheader ..."
autoheader
echo "automake ..."
automake
echo "autoconf ..."
autoconf
echo "Finished."

